# Generated by Django 3.2.9 on 2021-12-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20211218_1641'),
    ]

    operations = [
    ]
