# Generated by Django 3.2.9 on 2021-12-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0006_auto_20211219_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='producter',
            field=models.CharField(max_length=200, null=True, verbose_name='产品负责人'),
        ),
        migrations.AlterField(
            model_name='apistep',
            name='apimetod',
            field=models.CharField(choices=[('patch', 'patch'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('get', 'get')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
    ]
