# Generated by Django 3.2.9 on 2021-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20211219_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistep',
            name='apimetod',
            field=models.CharField(choices=[('delete', 'delete'), ('put', 'put'), ('post', 'post'), ('patch', 'patch'), ('get', 'get')], default='get', max_length=200, null=True, verbose_name='请求方法'),
        ),
    ]
